### ISSUE TITLE
Cart container has its class changed on first load.

### ISSUE THREAD

**Issue by fabien-h** [reactionimp/icemachinesplus#121]
### Expected behaviour

The cart icon container should have the class `cart-container` all the time.

### Actual behaviour

On the first load, the cart container has the class `accounts` that replaces his `cart-container` class.
Then when you navigate to any other page that triggers a nav bar re-render (like form the home to a product page or from a product page to the home), or when you log in or out, the right class, `cart-container` is applied.

The super weird part is that when you inspect the button with the react inspector, you can see that is at the right class. So the virtual DOM is right. But it looks like there is direct DOM manipulation to change that class. And I cannot find where this happens.

### Steps to reproduce the behaviour

Load the home page from scratch and look at the cart button ; top right.

### Versions

Node: 9.10.0
NPM: 5.8.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.29.0
Reaction: 1.9.0
Reaction branch: master
Docker: 18.03.0-ce

**Comment by fabien-h** [comment]
To make the issue more clear, here are views of the icon before and after the first js load.

And the result in the basic chrome inspector and the react inspector.

=> The virtual and the actual DOM are not in sync. Something is overwriting it. (and anything that re-render the navbar like changing view or logging in fixes that sync)

<img width="143" alt="screen shot 2018-04-09 at 09 00 53" src="https://user-images.githubusercontent.com/2682701/38483825-92310fe2-3bd4-11e8-8534-ee43afdf1a93.png">

<img width="131" alt="screen shot 2018-04-09 at 09 01 05" src="https://user-images.githubusercontent.com/2682701/38483828-9433282a-3bd4-11e8-8106-3bd0b7fbc1cb.png">

<img width="520" alt="screen shot 2018-04-09 at 08 56 31" src="https://user-images.githubusercontent.com/2682701/38483791-7465717e-3bd4-11e8-9ba0-4b369fea07d5.png">

<img width="727" alt="screen shot 2018-04-09 at 08 57 25" src="https://user-images.githubusercontent.com/2682701/38483770-69b88fae-3bd4-11e8-84f2-caf32fabf818.png">

**Comment by prinzdezibel** [comment]
@fabien-h How is the prerendered HTML from `http://67.205.163.60/getprerenderdata?pagepath=` updated when the HTML markup changes?

**Comment by fabien-h** [comment]
The service can be called to update a specific route or list of routes => if you post an array of urls to `/postpagestoprerender` they will be added to the render queue.

But we don't use it that way. Every hour, the pre-render service restarts a couple of chrome headless instances and call the website sitemap to get a list of all the urls. And then proceeds to caches them all.

There is a queue with all the routes to render. When a route is rendered, it is removed from the queue. When the routes are called every hour, only the routes that are not in the current queue are added to that queue.

=> Currently, the entire site takes approximately 1h30 to render. I want to make sure that this will stay a marginal load for the server so there is a delay between two data calls. But it could go faster.

=> A route can be out of date for a maximum of 1h30 so we should very rarely see any sync issue. And as soon as the fresh data are called, the template is hydrated with fresh data ; so a sync issue would always be fixed in a matter of seconds.

**Comment by prinzdezibel** [comment]
@fabien-h I'm not 100% certain if the error really stems from the react-addons-create-fragment. I realize that a missing key prop on React components may cause the component to mount/unmount on order changes, but I can't explain why this should affect hydration (albeit I'm not very deep into the mechanics of the hydration process, so not sure at all).

Another path worth to investigate: In file  `icemachinesplus/imports/plugins/custom/custom-navbar/client/components/navbar.js` I saw this markup:
```
 {/* That part tells the pre-renderer that the header is ready */}
      <div id="prerenderHeaderForHeadlessReady" />
```
I'm not sure what the purpose of this is. I couldn't find any other code refering to it. I guess it's used by the prerender.io servers. What made me suspicious was the fact that this element does not appear at the end of the header markup, but somewhere inbetween (renderTagNav function). Is this intentional?

**Comment by fabien-h** [comment]
<img width="157" alt="screen shot 2018-04-11 at 00 08 01" src="https://user-images.githubusercontent.com/2682701/38586052-7017a242-3d1c-11e8-9264-d41730815c70.png">

The cart container still does not have the right class.

**Comment by fabien-h** [comment]
Ok, we don't have time for this.

I added a empty div. The account class is now added to that empty div. It solves the issue.

```JavaScript
{visibility.mainDropdown && <Components.MainDropdown />}
{/** Do not remove the following empty div.
It solves a bug where the account class is added
to the div after the MainDropdown */}
<div />
{this.renderCartContainerAndPanel()}
```
